name = "soda100827/blossom_rivals"
description = "i love you rivals."
version = "0.1.0"
authors = ["soda100827"]
includes = ["pesde.toml", "src/*"]

[engines]
pesde = "^0.7.1"
lune = "=0.10.4"

[target]
build_files = ["src"]
environment = "roblox"
# Remove bin AND lib, if you are not publishing to the registry
bin = "src/main.luau" # Remove this, if this is not a binary
lib = "src/init.luau" # Remove this, if this is not a library

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
# Example dependency below, remove it if you don't need it
promise = { wally = "evaera/promise", version = "^4.0.0" }

[dev_dependencies]
darklua = { repo = "Stefanuk12/darklua", rev = "57e85a0c92db3d0df067ba037ac67ce453b85a66", target = "lune" }
luau_defs = { repo = "rocult/luau-defs", rev = "e628aec6fabb5acfd28f1bc6a18a1c7950122d2c", target = "luau" }

luau_lsp = { name = "pesde/luau_lsp", version = "^1.61.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.6.1", target = "lune" }
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
selene = { name = "pesde/selene", version = "^0.29.0", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.3.1", target = "lune" }
