# Please read this -> https://github.com/Stefanuk12/luarmor-deploy-action/tree/main
# NOTE: this only works if you use 2captcha solver

name: Deploy Script to Luarmor

on:
  workflow_dispatch:

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Pesde
        uses: lumin-org/setup-pesde@v0.4.1
        with:
          cache: true

      - name: Install dependencies
        run: pesde install

      - name: Darklua
        run: |
          ~/.pesde/bin/darklua -V
          darklua=$(find ~/.pesde/bin/.tool_storage -type f -name 'darklua*' -printf '%T@ %p\n' | sort -nr | head -n1 | cut -d' ' -f2-)
          "$darklua" process src/init.luau dist.lua -c .meta/.darklua.json

      - name: Upload dist.lua artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist.lua

  deploy:
    runs-on: [self-hosted]
    needs:
      - bundle

    steps:
      - name: Download dist.lua artifact
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: ./

      - name: Deploy to Luarmor
        uses: stefanuk12/luarmor-deploy-action@v2.0.0
        with:
          twocaptcha-api-key: ${{ secrets.TWOCAPTCHA_API_KEY }}
          api-key: ${{ secrets.LUARMOR_API_KEY }}
          script-id: "26bf4fbf77075cc4dc118a1432bdef95" # Rocult Paid
          file: "dist.lua"

      - name: Deploy to Luarmor
        uses: stefanuk12/luarmor-deploy-action@v2.0.0
        with:
          twocaptcha-api-key: ${{ secrets.TWOCAPTCHA_API_KEY }}
          api-key: ${{ secrets.LUARMOR_API_KEY }}
          script-id: "b51589a899a693b4da98f86bbfb79c23" # Rocult Free
          file: "dist.lua"
